apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-web-first
spec:
  replicas: 4
  selector:
    matchLabels:
      app: k8-web-first
  template:
    metadata:
      labels:
        app: k8-web-first
    spec:
      containers:
      - name: k8-web-first
        image: usa19/renisis-tech
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 3000
